### ISSUE TITLE
Document how to use libraries that expect `window`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper.svelte.technology#44]
These frequently break server-rendering. It's easily fixed with dynamic `import()`

**Comment by eyeseast** [comment]
Ran into this myself. If you need a good example, see [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js).

**Comment by mindrones** [comment]
Linking [this](https://github.com/webpack/webpack/issues/8304) in case someone else will have issues with `Path2D`.

**Comment by mindrones** [comment]
closing as #45 has been merged
